### ISSUE TITLE
CS score in the paper, table 2

### ISSUE THREAD

**Issue by JurijsNazarovs** [yashkant/concat-vqa#8]
Hello,

For the table 2 in the paper, where CS score is reported, is it CS or CS-BT in the code? CS is computed for revqa, and CS-BT is computed for revqa_bt.

**Comment by yashkant** [comment]
DA (data augmentation) only denotes source of train data, we do not change test/validation data [CS, or VQA accuracy] across experiments since that would introduce inconsistent evaluation. 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/17530895/175371922-0a6592a5-491b-4d4b-8a19-3d7a035615eb.png">
