### ISSUE TITLE
Script to generate negatives

### ISSUE THREAD

**Issue by JurijsNazarovs** [yashkant/concat-vqa#9]
Hello,

Could you please share the script to generate a list of negatives? Negatives, which we load from .pkl? 

Jurijs

**Comment by yashkant** [comment]
Hi,

I just released all the internal code related to this project [https://github.com/yashkant/vilbert-textvqa/tree/vqa-reb-branch].

You might find the scripts you need here — https://github.com/yashkant/vilbert-textvqa/tree/vqa-reb-branch/script/vqa-re

Since it’s been so long I have looked at the original code, I have forgotten most parts. 

Also, would like to apologize for how messy it is, I didn’t write code well then (not sure if I do now :P)

**Comment by JurijsNazarovs** [comment]
Thank you! No worries about the code, I am glad to see any version, to understand the main idea.
